### ISSUE TITLE
发布动态选择定位那里点击选择后返回闪退

### ISSUE THREAD

**Issue by dary123** [Jetpack-Missionary/Jetpack-From-Java-To-Kotlin#2]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{5d146ff position=0 id=-1, oldPos=0, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{b308500 VFED..... .F....ID 0,160-720,1344 #7f08012a app:id/rv}, adapter:com.kunminx.jetpack_java.common_ui.adapter.LocationAdapter@a2ed139, layout:androidx.recyclerview.widget.LinearLayoutManager@4c4a37e, context:com.kunminx.jetpack_java.sample_01_lifecycles.ui.LifecycleLocationActivity@bdb7196

**Comment by KunMinX** [comment]
@dary123 
感谢反馈，这个问题我们先记下了，目前暂时将定位列表的刷新速度减慢。

**Comment by KunMinX** [comment]
@dary123 
已修复，目前采取重写 layoutManager 的方式解决
