### ISSUE TITLE
包导入错误

### ISSUE THREAD

**Issue by liyanfei250** [Jetpack-Missionary/Jetpack-From-Java-To-Kotlin#5]

**Comment by liyanfei250** [comment]
e: D:\Jetpack-From-Java-To-Kotlin\jetpack_kotlin\src\main\java\com\flywith24\jetpack_kotlin\sample_04_databinding\ui\adapter\DataBindingLocationAdapter.kt: (7, 55): Unresolved reference: locationDiffCallback

**Comment by liyanfei250** [comment]
import com.flywith24.jetpack_kotlin.common_ui.adapter.momentDiffCallback   这个momentDiffCallback 报红

**Comment by Flywith24** [comment]
已修改，pull 最新代码即可
